const DEFAULT_STATUS_SUCCESS = "ok";
const DEFAULT_STATUS_ERROR = "error";

const NAVIGATION_DELAY_SHORT = 500;
const NAVIGATION_DELAY_NORMAL = 1500;
const NAVIGATION_DELAY_LONG = 5000;

const NAVIGATION_DELAYS = {
    SHORT: NAVIGATION_DELAY_SHORT,
    NORMAL: NAVIGATION_DELAY_NORMAL,
    LONG: NAVIGATION_DELAY_LONG,
};

const NAVIGATION_DELAY_DEFAULT = NAVIGATION_DELAY_NORMAL;

export {
    DEFAULT_STATUS_SUCCESS,
    DEFAULT_STATUS_ERROR,
    NAVIGATION_DELAY_DEFAULT,
    NAVIGATION_DELAYS,
};
